
export interface BnakerDetail {

    id: number,
    punchinClaimId: string,
    insurerClaimId: string,
    punchinBankerId: string,
    claimInwardDate: Date,
    borrowerName: string,
    borrowerContactNumber: string,
    borrowerCity: string,
    borrowerState: string,
    borrowerPinCode: string,
    borrowerEmailId: string,
    borrowerAlternateContactNumber: string,
    borrowerAlternateContactDetails: string,
    borrowerDob: Date,
    loanAccountNumber: string,
    borrowerAddress: string,
    loanType: string,
    loanDisbursalDate: Date,
    loanOutstandingAmount: number,
    loanAmount: number,
    loanAmountPaidByBorrower: number,
    loanAmountBalance: number,
    branchCode: string,
    branchName: string,
    branchAddress: string,
    branchPinCode: string,
    branchCity: string,
    branchState: string,
    loanAccountManagerName: string,
    accountManagerContactNumber: string,
    insurerName: string,
    masterPolNumber: string,
    policyNumber: string,
    policyStartDate: Date,
    policyCoverageDuration: number,
    policySumAssured: number,
    nomineeName: string,
    nomineeRelationShip: string,
    nomineeContactNumber: string,
    nomineeEmailId: string,
    nomineeAddress: string,
    claimStatus: string

}

